# Generated by Django 4.1 on 2022-09-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
